const BlogData = [
  {
    id: 1,
    date: "August 19, 2022",
    catgeory: "Business",
    title: "Sensex surges 508 points; Nifty tops 14,450-mark." ,
    cover: "/images/singlepage/blog-1.jpg",
    para: "quity benchmark Sensex rallied 508 points on Monday, tracking gains in index majors ICICI Bank, Reliance Industries and Axis Bank amid a mixed trend in global markets.",
    desc: "The 30-share BSE index ended 508.06 points or 1.06 per cent higher at 48,386.51. Similarly, the broader NSE Nifty jumped 143.65 points or 1 per cent to 14,485. Axis Bank was the top gainer in the Sensex pack, rallying over 4 per cent, followed by ICICI Bank, UltraTech Cement, HUL, SBI, PowerGrid, Bajaj Auto and Reliance Industries.On the other hand, HCL Tech, HDFC Bank, Maruti, Sun Pharma and TCS were among the laggards.“Domestic equities shrugged off rising COVID-19 cases and rebounded mainly led by sharp recovery in financials,” said Binod Modi, Head Strategy at Reliance Securities.Barring pharma, most of key sectoral indices traded in green. Strong March quarter performance led ICICI Bank to recovery sharply, while HCL Technologies witnessed sell-off due to subdued 4Q performance, he added..",
  },
  {
    id: 2,
    date: "August 15, 2022",
    catgeory: "Politics",
    title: "Rajnath Singh slams opposition, says there should be no politics over border security with china",
    cover: "/images/singlepage/blog-2.jpg",
    para: "Jodhpur (Rajasthan) [India] August 13 (ANI): Defence Minister Rajnath Singh on Saturday attacked the opposition leaders and said that there should be no politics over border security with China.",
    desc: "On the occasion of the 385th birth anniversary celebration of Veer Durgadas Rathore in Jodhpur’s Salwa Kalan area, Minister Rajnath Singh unveiled the statue of Veer Durgadas Rathore and said, “They say ‘China did this,’ ‘China did that.’ To such political leaders, I say- There should be no politicisation whenever it is a matter of the honour of the country. It is these brave sons who go and guard the borders.Praising the mothers of all the brave hearts, Rajnath Singh said, “This is the land of brave women and I bow my head at the feet of all the mothers who gave birth to such brave men Slamming the Opposition leaders he said, “Those who raise questions against the national security, I as the Defense Minister, want to assure them that no matter how hard it gets I will not let the honour of India get sacrificed.“Today because of Prime Minister Narendra Modi, India’s security circle has become stronger than ever before, India is no longer counted among the weak countries of the world and is counted among the most powerful countries of the world,” he added. Further, he lauded Veer Durgadas Rathore and said, “If there can be any example of social unity and harmony, then it was Durga Das Ji. He was born in an ordinary family but his name is recorded in the pages of history with his extraordinary personality and devotion to Swami.",
  },
  {
    id: 3,
    date: "August 20, 2022",
    catgeory: "Education",
    title: "How to become an international school teacher: Guidelines to develop skills, knowledge and practice",
    cover: "/images/singlepage/blog-3.jpg",
    para: "The K-12 education sector in India has transformed at a rapid pace in the last deipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
    desc: "sk a school head what is one of the most challenging tasks for them today, and the immediate answer is going to be staff recruitment, training, and retaining. They point out a range of desirable traits and attitudes needed in any recruit.It is a given fact that apart from the necessary subject qualifications and content knowledge a teacher needs to be able to teach students in an innovative manner to keep student engagement and involvement high along with the use of technology for teaching and assessments.Given that the expectations from a teacher to innovate and incorporate 21st-century skills in the classrooms are increasingly becoming more demanding, what is that a young aspiring teacher or a student at the graduate education school should equip oneself with? I would like to give some pointers of expectations from a teacher, the list is surely not exhaustive but will outline the expectations of a teacher. The pointers mentioned here are in no particular order, as all of them are prerequisites in any international schoolteacher.Skills needed to become an international school teacher 1. Pedagogical skills: Teachers should be able to develop tasks that are intellectually meaningful that ensure that all students can understand, participate and collaborate in a class.The array of pedagogical skills should include the right selection of teaching methods, presentation skills, questioning skills along with the aid of technology for both effective teaching and assessments 2. Reflective skills: The ability to critically reflect on their own practices and improve from them, purposeful inquiry about ways to teach will shape their ways towards the teaching-learning process Apart from these are a range of skills like Interpersonal skills, collaborative skills, personal skills, management skills "
  },
  {
    id: 4,
    date: "August 21, 2022",
    catgeory: "Sports",
    title: "India among 8 teams to qualify for women's T20 competition at Birmingham Commonwealth Games 2022",
    cover: "/images/singlepage/blog-4.jpg",
    para: "The International Cricket Council (ICC) on Monday named India, Australia, New Zealand, Pakistan, South Africa, a country from the Caribbean region and hosts England in an eight-team T20 tournament of the 2022 Commonwealth Games, which will take place at Edgbaston between July 28 and August 8, 2022.",
    desc: "It is only the second time that cricket will be featured at the Commonwealth Games after South Africa's victory in the ODI tournament in 1998, and the first time women's cricket has been part of it. A yet-to-be-determined qualifier will complete the eight-team competition, the International Cricket Council (ICC) and the Commonwealth Games Federation (CGF) announced.As per the qualification process, the winner of a designated Qualifying event will determine which country from the Caribbean region gets to participate as athletes will be representing their individual countries and not the West Indies as they would at ICC events, a joint statement said. India captain Harmanpreet Kaur said: “It’s great to be confirmed a place in the Commonwealth Games. We are raring to go, confident of doing well after having made the final of the ICC Women’s T20 World Cup in Australia last year.“It is an awesome opportunity for both the women’s game and cricket to make a mark at the prestigious multi-discipline Games and we hope to return with loads of good memories.CGF President Louise Martin said: Cricket is a sport that is synonymous with the Commonwealth and we are so excited to have it back in the Games for the first time since the men’s competition at Kuala Lumpur 1998.“The debut of women’s T20 cricket will be a historic moment for Commonwealth Sport and a wonderful showcase for women’s sport across the world,",
  },
  {
    id: 5,
    date: "January 10, 2022",
    catgeory: "Technology",
    title: "ISRO's PSLV-C51 puts Brazil's Amazonia-1 satellite into orbit",
    cover: "/images/singlepage/blog-5.jpg",
    para: "India on Sunday morning successfully placed into orbit Brazil's earth observation satellite Amazonia-1in a textbook style. The Polar Satellite Launch Vehicle-C51 (PSLV-C51) blasted off from the first launch pad at 10.24 a.m. laden with 19 satellites including Amazonia-1.",
    desc: " At 10.24 a.m. the 44.4 metre tall PSLV-C51 rocket blasted off from the first launch pad here laden with 19 satellites-foreign and Indian- and slowly rose-up towards the skies with thick orange flame at its tail.The rocket slowly gained speed as it went up while emitting a rolling thunder sound. Seventeen minutes into its flight the rocket slung its primary passenger the Brazilian satellite Amazonia-1 - the first of the 19 satellites- into its intended Sun Synchronous Orbit.Amazonia-1 is the optical earth observation satellite of National Institute for Space Research (INPE). This satellite would further strengthen the existing structure by providing remote sensing data to users for monitoring deforestation in the Amazon region and analysis of diversified agriculture across the Brazilian territory, Indian Space Research Organisation (ISRO) said.With this India has slung 329 foreign satellites till date. If all goes well, then India will end the mission orbiting a total of 342 foreign satellites, all for a fee.India's first space mission for 2021 is one of the longest for a PSLV rocket is expected to conclude 1 hour, 55 minutes and 7 seconds into its flight. The rocketing is a fully commercial one of NewSpace India Ltd (NSIL).The 18 co-passenger satellites include four from IN-SPACe (three UNITYsats from consortium of three Indian academic institutes (Jeppiaar Institute of Technology, Sriperumbudur, G.H.Raisoni College of Engineering, Nagpur and Sri Shakthi Institute of Engineering and Technology, Coimbatore), one Satish Dhawan Sat from Space Kidz India) with an engraved picture of Prime Minister Narendra Modi as well as Bhagavad Gita in a flash.",
  },
  {
    id: 6,
    date: "August 18, 2022",
    catgeory: "Entertainment",
    title: "Thiruchitrambalam Review and Twitter Reactions: Dhanush-Nithya Menen are show stealers in entertaining drama",
    cover: "/images/singlepage/blog-6.jpg",
    para: "Thiruchitrambalam Review and Twitter Reactions: Dhanush and Nithya Menen's latest film is a family entertainer. Thiruchitrambalam has released on August 18 in cinema halls. Know how viewers are reacting to it.",
    desc: "After his action avatar as The Lone Wolf in the Netflix release The Gray Man, Dhanush's new romantic drama Thiruchitrambalam has released in cinema halls on August 18. Fans have been queuing outside the cinema halls to catch the film on the big screen and scenes outside the cinema halls in Tamil Nadu are proof of the massive buzz the movie has created among the viewers. So how good Dhanush and Nithya Menen's Thiruchitrambalam is? Let's find out. On social media, fans have been sharing positive reviews of Dhanush's latest release. Interestingly, more than Dhanush, Nithya Menen's role and performance in the film are being praised. Dhanush's fans have been all hearts for Nithya's charm and lauded the emotional depth she brings to the character. Some even mentioned that Nithya has managed to be the true show-stealer in the film and even outshines Dhanush in their scenes together. The music from Anirudh lends a different feel to the film. Viewers said that the film is filled with warm and simple moments and that makes it a family film. While Dhanush breaks away from his mass image, he lets other actors shine in the movie. It will be interesting to see how Thiruchitrambalam performs at the box office in the coming days. ",
  },
  {
    id: 7,
    date: "August 15, 2022",
    catgeory: " Business & Finance",
    title: "India now creating unicorns faster than china",
    cover: "/images/singlepage/blog-7.jpg",
    para: "The data suggests that India is now minting unicorns faster than any other country in the world, leaving China, which has 174 unicorns, behind to take the crown. Israel closely follows India with 96 unicorns and is on its way to entering the three-figure mark.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 8,
    date: "August 18, 2022",
    catgeory: " Sports",
    title: "GER vs ISL, 2022 FIFA World Cup Qualifier Live streaming: When and where to watch Germany vs Iceland match?",
    cover: "/images/singlepage/blog-8.jpg",
    para: "Germany are all set to host Iceland at the MSV-Arena in Germany for a 2022 FIFA World Cup qualifier match. The two sides will play each other on Friday (March 26), with a kick-off time set to 1:15 AM IST. In their last international encounter, Germany lost to Spain by a horrific 6-0 scoreline back in November of 2020. A hattrick came from Ferran Torres in the match. Alvaro Morata, Manchester City midfielder Rodri and Real Sociedad's Mikel Oyarzabal all got on the scoresheet to seal the deal for La Roja.",
    desc: "Meanwhile, Iceland were handed a 4-0 defeat by England in their last international fixture at the Wembley Stadium in November of 2020. Declan Rice, Mason Mount, Phil Foden all put a goal past the Iceland net to secure a win for their side. Germany remain the dominant side in their last 4 meetings with Iceland with three victories and one draw. Everton midfielder Gylfi Sigurdsson remains a doubt and isn't expected in the lineup against Germany on Thursday. Germany: Manuel Neuer, Joshua Kimmich, Nikas Sule, Antonio Rudiger, Philipp Max, Toni Kroos, Leon Goretzka, Serge Gnabry, Florian Neuhaus, Leroy Sane, Timo Werner Iceland: Hannes Por Halldorsson, Alfons Sampsted, Sverrir Ingi Ingason, Hordur Bjorgvin Magnusson, Hjortur Hermannsson, Ari Freyr Skulason, Johann Berg Gudmundsson, Birkir Bjarnason, Runar Mar Sigurjonsson, Albert Gudmundsson, Jon Daoi Bodvarsson",
  },
  {
    id: 2,
    date: "August 15, 2022",
    catgeory: "Business ",
    title: "These stocks witness a huge volume burst in the last leg of the trading session",
    cover: "/images/singlepage/blog-9.jpg",
    para: "TCNS Clothing, V-Guard Industries, and Vaibhav Global Limited have witnessed volume burst in the last 75 minutes of the trade. As the saying goes, the first, as well as the last hour of each trading session, is the most important and active in terms of price & volume.",
    desc: "More so, the activity in the last hour is said to be of utmost importance because most of the pro-traders and institutions are active at this time. Hence, when a stock sees a good spike in volume in the last leg of the trade along with a price rise, it is considered a pro, and institutions have a keen interest in the stock. Market participants should keep a close watch on these stocks as they can witness good momentum in the short to medium term.So, based on this principle, we have shortlisted three stocks that have witnessed volume burst in the last leg of the trade along with price rise.TCNS Clothing: The stock traded flat for the most part of the day but witnessed strong momentum towards the end. The stock closed 7.53% higher, but about 2.50% of this rally came in the last 75 minutes. About 70% of the day s volume was recorded during this period. With stronger volumes, it is expected to be volatile with a positive bias for upcoming days. V-Guard Industries: The stock climbed 4.79% on Friday. It formed higher highs on the technical chart which is a positive sign. It traded positively throughout the day and volumes continued to rise. With above-average volume, we can expect it to be trading higher in times to come.Vaibhav Global Limited: The scrip soared about 4.43% during the day. Strong buying interest was seen at lower levels which propelled the stock above its 20-DMA. Above-average volumes were recorded recently, and such strong price action shall put the stock in a sweet position for upcoming days.",
  },  
]

export default BlogData
